server:
   port: 8079
   
spring:
   application.name: gateway
   cloud:
     gateway:
       default-filters:
       - PrefixPath=/
       routes:
      # ======================
       - id: users
         uri: lb://users
         predicates:
         - Path=/users/**
         filters:
         - StripPrefix=1
      # ======================
