server:
   port: 8079
   
spring:
   application.name: gateway
   cloud:
     gateway:
       default-filters:
       - PrefixPath=/
       routes:
      # ======================
       - id: users
         uri: lb://users
         predicates:
         - Path=/users/**
         filters:
         - StripPrefix=1
      # ======================
      #  - id: emails
      #    uri: lb://emails
      #    predicates:
      #    - Path=/emails/**
      #    filters:
      #    - StripPrefix=1
      # ======================
